/* =====================================================================
   空港 [コード, 名称, 愛称(ハンドブック 2.3.2.4.9.8), 天候案内用の地名, 英語名]
   ===================================================================== */
const AIRPORTS_DOM = [
  ['CTS', '新千歳空港', '', '札幌', 'New Chitose Airport'],
  ['OKD', '丘珠空港', '', '札幌', 'Okadama Airport'],
  ['HKD', '函館空港', '', '函館', 'Hakodate Airport'],
  ['AKJ', '旭川空港', '北海道のまん中旭川空港', '旭川', 'Asahikawa Airport'],
  ['KUH', '釧路空港', 'たんちょう釧路空港', '釧路', 'Kushiro Airport'],
  ['OBO', '帯広空港', 'とかち帯広空港', '帯広', 'Obihiro Airport'],
  ['MMB', '女満別空港', '', '女満別', 'Memanbetsu Airport'],
  ['SHB', '中標津空港', '', '中標津', 'Nakashibetsu Airport'],
  ['RIS', '利尻空港', '', '利尻', 'Rishiri Airport'],
  ['OIR', '奥尻空港', '', '奥尻', 'Okushiri Airport'],
  ['WKJ', '稚内空港', '', '稚内', 'Wakkanai Airport'],
  ['AOJ', '青森空港', '', '青森', 'Aomori Airport'],
  ['MSJ', '三沢空港', '', '三沢', 'Misawa Airport'],
  ['AXT', '秋田空港', '', '秋田', 'Akita Airport'],
  ['HNA', '花巻空港', 'いわて花巻空港', '花巻', 'Hanamaki Airport'],
  ['GAJ', '山形空港', 'おいしい山形空港', '山形', 'Yamagata Airport'],
  ['SYO', '庄内空港', '', '庄内', 'Shonai Airport'],
  ['SDJ', '仙台空港', '', '仙台', 'Sendai Airport'],
  ['HND', '羽田空港', '', '東京', 'Haneda Airport'],
  ['NRT', '成田空港', '', '成田', 'Narita Airport'],
  ['HAC', '八丈島空港', '', '八丈島', 'Hachijojima Airport'],
  ['KIJ', '新潟空港', '', '新潟', 'Niigata Airport'],
  ['TOY', '富山空港', '', '富山', 'Toyama Airport'],
  ['KMQ', '小松空港', '', '小松', 'Komatsu Airport'],
  ['NTQ', '能登空港', '', '能登', 'Noto Airport'],
  ['MMJ', '松本空港', '', '松本', 'Matsumoto Airport'],
  ['FSZ', '静岡空港', '', '静岡', 'Shizuoka Airport'],
  ['NGO', '中部国際空港', 'セントレア空港', '名古屋', 'Chubu Centrair Airport'],
  ['NKM', '県営名古屋空港', '', '名古屋', 'Nagoya Airfield'],
  ['ITM', '伊丹空港', '', '大阪', 'Itami Airport'],
  ['KIX', '関西国際空港', '', '関西', 'Kansai Airport'],
  ['UKB', '神戸空港', '', '神戸', 'Kobe Airport'],
  ['SHM', '南紀白浜空港', '熊野白浜リゾート空港', '南紀白浜', 'Nanki-Shirahama Airport'],
  ['TJH', '但馬空港', '', '但馬', 'Tajima Airport'],
  ['OKJ', '岡山空港', '岡山桃太郎空港', '岡山', 'Okayama Airport'],
  ['HIJ', '広島空港', '', '広島', 'Hiroshima Airport'],
  ['IZO', '出雲空港', '出雲縁結び空港', '出雲', 'Izumo Airport'],
  ['YGJ', '米子空港', '', '米子', 'Yonago Airport'],
  ['TTJ', '鳥取空港', '鳥取砂丘コナン空港', '鳥取', 'Tottori Airport'],
  ['OKI', '隠岐空港', '隠岐世界ジオパーク空港', '隠岐', 'Oki Airport'],
  ['IWJ', '石見空港', '', '石見', 'Iwami Airport'],
  ['UBJ', '山口宇部空港', '', '山口宇部', 'Yamaguchi Ube Airport'],
  ['TKS', '徳島空港', '徳島阿波おどり空港', '徳島', 'Tokushima Airport'],
  ['TAK', '高松空港', '', '高松', 'Takamatsu Airport'],
  ['KCZ', '高知空港', '高知龍馬空港', '高知', 'Kochi Airport'],
  ['MYJ', '松山空港', '', '松山', 'Matsuyama Airport'],
  ['FUK', '福岡空港', '', '福岡', 'Fukuoka Airport'],
  ['KKJ', '北九州空港', '', '北九州', 'Kitakyushu Airport'],
  ['HSG', '佐賀空港', '', '佐賀', 'Saga Airport'],
  ['NGS', '長崎空港', '', '長崎', 'Nagasaki Airport'],
  ['IKI', '壱岐空港', '', '壱岐', 'Iki Airport'],
  ['TSJ', '対馬空港', '', '対馬', 'Tsushima Airport'],
  ['FUJ', '福江空港', '', '五島福江', 'Fukue Airport'],
  ['KMJ', '熊本空港', '阿蘇くまもと空港', '熊本', 'Kumamoto Airport'],
  ['AXJ', '天草空港', '', '天草', 'Amakusa Airport'],
  ['OIT', '大分空港', '', '大分', 'Oita Airport'],
  ['KMI', '宮崎空港', '宮崎ブーゲンビリア空港', '宮崎', 'Miyazaki Airport'],
  ['KOJ', '鹿児島空港', '', '鹿児島', 'Kagoshima Airport'],
  ['TNE', '種子島空港', '', '種子島', 'Tanegashima Airport'],
  ['KUM', '屋久島空港', '', '屋久島', 'Yakushima Airport'],
  ['ASJ', '奄美空港', '', '奄美', 'Amami Airport'],
  ['KKX', '喜界空港', '', '喜界島', 'Kikai Airport'],
  ['TKN', '徳之島空港', '', '徳之島', 'Tokunoshima Airport'],
  ['OKE', '沖永良部空港', '', '沖永良部', 'Okinoerabu Airport'],
  ['RNJ', '与論空港', '', '与論', 'Yoron Airport'],
  ['OKA', '那覇空港', '', '那覇', 'Naha Airport'],
  ['UEO', '久米島空港', '', '久米島', 'Kumejima Airport'],
  ['KTD', '北大東空港', '', '北大東', 'Kitadaito Airport'],
  ['MMD', '南大東空港', '', '南大東', 'Minamidaito Airport'],
  ['MMY', '宮古空港', '', '宮古', 'Miyako Airport'],
  ['SHI', '下地島空港', '', '下地島', 'Shimojishima Airport'],
  ['ISG', '石垣空港', '南ぬ島石垣空港', '石垣', 'Ishigaki Airport'],
  ['OGN', '与那国空港', '', '与那国', 'Yonaguni Airport'],
];
const AIRPORTS_INT = [
  ['ICN', 'ソウル仁川空港', '', 'ソウル', 'Seoul Incheon Airport'],
  ['GMP', 'ソウル金浦空港', '', 'ソウル', 'Seoul Gimpo Airport'],
  ['PUS', '釜山空港', '', '釜山', 'Busan Gimhae Airport'],
  ['PEK', '北京首都空港', '', '北京', 'Beijing Capital Airport'],
  ['DLC', '大連空港', '', '大連', 'Dalian Airport'],
  ['TSN', '天津浜海空港', '', '天津', 'Tianjin Binhai Airport'],
  ['PVG', '上海浦東空港', '', '上海', 'Shanghai Pudong Airport'],
  ['SHA', '上海虹橋空港', '', '上海', 'Shanghai Hongqiao Airport'],
  ['TPE', '台北桃園空港', '', '台北', 'Taipei Taoyuan Airport'],
  ['TSA', '台北松山空港', '', '台北', 'Taipei Songshan Airport'],
  ['KHH', '高雄空港', '', '高雄', 'Kaohsiung Airport'],
  ['CAN', '広州白雲空港', '', '広州', 'Guangzhou Baiyun Airport'],
  ['HKG', '香港空港', '', '香港', 'Hong Kong Airport'],
  ['MNL', 'マニラ空港', '', 'マニラ', 'Manila Airport'],
  ['HAN', 'ハノイ空港', '', 'ハノイ', 'Hanoi Airport'],
  ['SGN', 'ホーチミン空港', '', 'ホーチミン', 'Ho Chi Minh City Airport'],
  ['BKK', 'バンコク・スワンナプーム空港', '', 'バンコク', 'Bangkok Suvarnabhumi Airport'],
  ['KUL', 'クアラルンプール空港', '', 'クアラルンプール', 'Kuala Lumpur Airport'],
  ['SIN', 'シンガポール・チャンギ空港', '', 'シンガポール', 'Singapore Changi Airport'],
  ['CGK', 'ジャカルタ空港', '', 'ジャカルタ', 'Jakarta Airport'],
  ['DEL', 'デリー空港', '', 'デリー', 'Delhi Airport'],
  ['BLR', 'ベンガルール空港', '', 'ベンガルール', 'Bengaluru Airport'],
  ['DOH', 'ドーハ・ハマド空港', '', 'ドーハ', 'Doha Hamad Airport'],
  ['SYD', 'シドニー空港', '', 'シドニー', 'Sydney Airport'],
  ['MEL', 'メルボルン空港', '', 'メルボルン', 'Melbourne Airport'],
  ['GUM', 'グアム空港', '', 'グアム', 'Guam Airport'],
  ['HNL', 'ホノルル空港', '', 'ホノルル', 'Honolulu Airport'],
  ['KOA', 'コナ空港', '', 'コナ', 'Kona Airport'],
  ['LAX', 'ロサンゼルス空港', '', 'ロサンゼルス', 'Los Angeles Airport'],
  ['SAN', 'サンディエゴ空港', '', 'サンディエゴ', 'San Diego Airport'],
  ['SFO', 'サンフランシスコ空港', '', 'サンフランシスコ', 'San Francisco Airport'],
  ['SEA', 'シアトル空港', '', 'シアトル', 'Seattle Airport'],
  ['YVR', 'バンクーバー空港', '', 'バンクーバー', 'Vancouver Airport'],
  ['ORD', 'シカゴ・オヘア空港', '', 'シカゴ', "Chicago O'Hare Airport"],
  ['DFW', 'ダラス・フォートワース空港', '', 'ダラス', 'Dallas Fort Worth Airport'],
  ['BOS', 'ボストン・ローガン空港', '', 'ボストン', 'Boston Logan Airport'],
  ['JFK', 'ニューヨーク・JFK空港', '', 'ニューヨーク', 'New York JFK Airport'],
  ['LHR', 'ロンドン・ヒースロー空港', '', 'ロンドン', 'London Heathrow Airport'],
  ['CDG', 'パリ・シャルル・ド・ゴール空港', '', 'パリ', 'Paris Charles de Gaulle Airport'],
  ['FRA', 'フランクフルト空港', '', 'フランクフルト', 'Frankfurt Airport'],
  ['HEL', 'ヘルシンキ空港', '', 'ヘルシンキ', 'Helsinki Airport'],
];
const AIRPORTS = [...AIRPORTS_DOM, ...AIRPORTS_INT];

// 「〇〇行き」の地名 [日本語, 英語]。ここに無い空港は、天候用の地名と英語名(Airportを除く)を使う
const BOUND = {
  CTS: ['札幌', 'Sapporo'], OKD: ['札幌丘珠', 'Sapporo Okadama'],
  HND: ['東京羽田', 'Tokyo Haneda'], NRT: ['東京成田', 'Tokyo Narita'],
  NGO: ['名古屋', 'Nagoya'], NKM: ['名古屋小牧', 'Nagoya Komaki'], ITM: ['大阪伊丹', 'Osaka Itami'], KIX: ['大阪関西', 'Osaka Kansai'],
  ICN: ['ソウル仁川', 'Seoul Incheon'], GMP: ['ソウル金浦', 'Seoul Gimpo'], PUS: ['釜山', 'Busan'],
  PEK: ['北京', 'Beijing'], TSN: ['天津', 'Tianjin'], CAN: ['広州', 'Guangzhou'], PVG: ['上海浦東', 'Shanghai Pudong'], SHA: ['上海虹橋', 'Shanghai Hongqiao'],
  TPE: ['台北桃園', 'Taipei Taoyuan'], TSA: ['台北松山', 'Taipei Songshan'],
  BKK: ['バンコク', 'Bangkok'], SIN: ['シンガポール', 'Singapore'], DOH: ['ドーハ', 'Doha'],
  ORD: ['シカゴ', 'Chicago'], DFW: ['ダラス・フォートワース', 'Dallas Fort Worth'], BOS: ['ボストン', 'Boston'], JFK: ['ニューヨーク', 'New York'],
  LHR: ['ロンドン', 'London'], CDG: ['パリ', 'Paris'],
};
