/* =====================================================================
   地域別の見どころ(ハンドブック 2.3.2.4.9.1〜.7 の地図資料より)
   [名前JA, 名前EN, 一言JA, 一言EN, メモ(PAには入らない)]
   一言に {N} があればそこに名前が入る。無ければ「名前は、一言」の形になる。
   ===================================================================== */
const LANDMARKS = [
{ r: '北海道', items: [
  ['知床半島', 'the Shiretoko Peninsula', '2005年に世界自然遺産に登録されました。', 'was registered as a World Natural Heritage Site in 2005.', 'MMBにILS18 APP時、OUTBOUNDで右側。流氷の接岸は1月下旬〜2月上旬頃。'],
  ['屈斜路湖', 'Lake Kussharo', '日本最大のカルデラ湖です。', 'is the largest caldera lake in Japan.', 'MMBへの降下中、通常右側。道北の「クッチャロ湖」と音が似ているので注意。'],
  ['摩周湖', 'Lake Mashu', '世界有数の透明度を誇る湖です。', 'is known as one of the clearest lakes in the world.', 'MMBへの降下中、通常右側。'],
  ['釧路湿原', 'the Kushiro Marsh', '日本最大の湿原で、1980年に国内で最初のラムサール条約登録湿地となりました。', 'is the largest wetland in Japan, and in 1980 it became the first wetland in the country registered under the Ramsar Convention.', '国立公園。'],
  ['阿寒湖', 'Lake Akan', '特別天然記念物のマリモで知られる湖です。', 'is famous for marimo, balls of algae designated as a Special Natural Monument of Japan.', 'MMBへの降下中、通常左側。周りに雌阿寒岳・雄阿寒岳。'],
  ['大雪山', 'the Daisetsuzan mountains', '北海道の中央高地を形作る山々の総称で、最高峰の旭岳は標高2,291メートル、北海道の最高峰です。', 'are a group of mountains in central Hokkaido; the highest peak, Mount Asahi, is 2,291 meters high and the highest point in Hokkaido.', '大雪山は一つの山の名称ではない。'],
  ['羊蹄山', 'Mount Yotei', '「蝦夷富士」とも呼ばれ、標高は1,898メートルです。', 'is also known as "Ezo Fuji", and is 1,898 meters high.', ''],
  ['支笏湖', 'Lake Shikotsu', '日本で2番目に深い湖で、最大水深は360メートルです。', 'is the second-deepest lake in Japan, with a maximum depth of 360 meters.', '千歳市にある。'],
  ['津軽海峡', 'the Tsugaru Strait', '最も狭いところで幅約18.7キロメートルです。', 'is about 18.7 kilometers wide at its narrowest point.', '最狭部は大間崎と汐首岬の間(HKD RNAV"Y"APPのSHIOK、RNAV"Z"APPのIKARU付近)。'],
  ['旭川', 'Asahikawa', '1902年1月25日に、観測史上最も低いマイナス41.0度を記録しました。', 'recorded the lowest temperature ever observed in Japan, minus 41 degrees Celsius, on January 25, 1902.', '話題。日本一寒い町と言われる陸別町は道東。'],
  ['タンチョウ', 'the red-crowned crane', '北海道の鳥で、JALのロゴマークのモチーフにもなっています。', 'is the bird of Hokkaido, and it is also the motif of the JAL logo.', '話題(見えるものではない)。'],
  ['北海道新幹線', 'the Hokkaido Shinkansen', '新青森と新函館北斗の間を結んでいます。', 'connects Shin-Aomori and Shin-Hakodate-Hokuto.', '話題。東北新幹線内(東京−盛岡間)の最高時速は320km/h。'],
] },
{ r: '東北', items: [
  ['岩木山', 'Mount Iwaki', '「津軽富士」とも呼ばれ、標高は1,625メートルです。', 'is also known as "Tsugaru Fuji", and is 1,625 meters high.', '青森空港の南西。'],
  ['白神山地', 'the Shirakami Mountains', '1993年に屋久島とともに日本で初めて世界自然遺産に登録されました。', "were registered in 1993, together with Yakushima, as Japan's first World Natural Heritage Sites.", '青森県南西部から秋田県北西部。'],
  ['十和田湖', 'Lake Towada', '日本で3番目に深い湖で、最大水深は326.8メートルです。', 'is the third-deepest lake in Japan, with a maximum depth of about 327 meters.', '青森県と秋田県にまたがる。'],
  ['田沢湖', 'Lake Tazawa', '日本一深い湖で、最大水深は423.4メートルです。', 'is the deepest lake in Japan, with a maximum depth of about 423 meters.', '世界では17番目。'],
  ['岩手山', 'Mount Iwate', '岩手県の最高峰で、標高は2,038メートルです。', 'is the highest mountain in Iwate Prefecture, at 2,038 meters.', '田沢湖のやや北東。'],
  ['三陸海岸', 'the Sanriku Coast', '海岸線の全長は約600キロメートルです。', 'has a coastline about 600 kilometers long.', '青森県南部から宮城県牡鹿(おしか)半島まで。'],
  ['北上川', 'the Kitakami River', '東北最大の河川で、長さは249キロメートルです。', 'is the largest river in the Tohoku region, 249 kilometers long.', ''],
  ['鳥海山', 'Mount Chokai', '「出羽富士」とも呼ばれ、標高は2,236メートルです。', 'is also known as "Dewa Fuji", and is 2,236 meters high.', '秋田県と山形県にまたがる。'],
  ['月山', 'Mount Gassan', '標高1,984メートルで、湯殿山、羽黒山とともに出羽三山に数えられます。', 'is 1,984 meters high and is one of the Three Mountains of Dewa, together with Mount Yudono and Mount Haguro.', '山形県の中央部。'],
  ['最上川', 'the Mogami River', '日本三大急流のひとつで、長さは229キロメートルです。', 'is one of the three fastest-flowing rivers in Japan, 229 kilometers long.', ''],
  ['朝日岳', 'the Asahi Mountains', '主峰の大朝日岳は標高1,870メートルです。', "{N}' main peak, Mount Oasahi, is 1,870 meters high.", '大朝日岳(おおあさひだけ)。出羽三山の南。'],
  ['松島', 'Matsushima', '日本三景のひとつです。', 'is one of the Three Most Scenic Views of Japan.', '日本三景は松島・天橋立・宮島。'],
  ['蔵王連峰', 'the Zao mountains', '主峰の熊野岳は標高1,841メートルです。', "{N}' main peak, Mount Kumano, is 1,841 meters high.", ''],
  ['阿武隈川', 'the Abukuma River', '長さ239キロメートルで、河口は仙台空港の南にあります。', 'is 239 kilometers long and flows into the sea just south of Sendai Airport.', ''],
  ['吾妻山', 'the Azuma mountains', '山形県と福島県の県境にある火山群で、最高峰の西吾妻山は標高2,035メートルです。', 'are a volcanic range on the border of Yamagata and Fukushima; the highest peak, Mount Nishi-Azuma, is 2,035 meters high.', ''],
  ['安達太良山', 'Mount Adatara', '標高1,728メートルの山です。', 'is 1,728 meters high.', '吾妻山の南東。'],
  ['磐梯山', 'Mount Bandai', '「会津富士」とも呼ばれ、標高は1,816メートルです。', 'is also known as "Aizu Fuji", and is 1,816 meters high.', '読みは「ばんだいさん」。猪苗代湖の北。'],
  ['猪苗代湖', 'Lake Inawashiro', '面積で日本4番目の湖です。', 'is the fourth-largest lake in Japan.', ''],
  ['東北三大祭り', 'the three great summer festivals of Tohoku', '青森ねぶた祭り(8月2日〜7日)、秋田竿燈まつり(8月3日〜6日)、仙台七夕まつり(8月6日〜8日)です。', 'are the Aomori Nebuta Festival, the Akita Kanto Festival and the Sendai Tanabata Festival, held in early August.', '話題。四大まつりは山形花笠まつり(8/5-7)を加える。'],
] },
{ r: '関東・中部', items: [
  ['那須連山', 'the Nasu mountains', '栃木県と福島県の県境付近に連なる山々です。', 'stretch along the border of Tochigi and Fukushima prefectures.', ''],
  ['日光連山', 'the Nikko mountains', '標高2,300〜2,500メートル級の山々からなり、最高峰の奥白根山は標高2,578メートル、関東以北の最高峰です。', 'are a range of peaks 2,300 to 2,500 meters high; the highest, Mount Okushirane at 2,578 meters, is the highest peak in the Kanto region and northward.', '男体山は中禅寺湖の近く、標高2,486m。'],
  ['霞ヶ浦', 'Lake Kasumigaura', '面積が日本で2番目に大きい湖です。', 'is the second-largest lake in Japan.', '面積220km²。'],
  ['筑波山', 'Mount Tsukuba', '標高877メートルの山です。', 'is 877 meters high.', ''],
  ['利根川', 'the Tone River', '長さ322キロメートルで日本第2位、「坂東太郎」とも呼ばれます。', 'is the second-longest river in Japan at 322 kilometers, and is also called "Bando Taro".', ''],
  ['伊豆七島', 'the Izu Islands', '伊豆大島、利島、新島、神津島、三宅島、御蔵島、八丈島の7つの島です。', 'are seven main islands: Izu Oshima, Toshima, Niijima, Kozushima, Miyakejima, Mikurajima and Hachijojima.', '北から順。'],
  ['富士山', 'Mount Fuji', '標高3,776メートル、2013年に世界文化遺産に登録されました。', 'is 3,776 meters high, and was registered as a World Cultural Heritage Site in 2013.', ''],
  ['富士五湖', 'the Fuji Five Lakes', '本栖湖、精進湖、西湖、山中湖、河口湖の5つの湖で、2013年に富士山とともに世界文化遺産に登録されました。', 'are Lake Motosu, Lake Shoji, Lake Sai, Lake Yamanaka and Lake Kawaguchi, which were registered as part of the Mount Fuji World Cultural Heritage Site in 2013.', '本栖(もとす)・精進(しょうじ)・西(さい)。'],
  ['駿河湾', 'Suruga Bay', '最深部の水深は2,500メートルに達し、日本で最も深い湾です。', 'is the deepest bay in Japan, reaching a depth of about 2,500 meters.', ''],
  ['南アルプス', 'the Southern Alps', '赤石山脈のことで、最高峰の北岳は標高3,193メートル、日本第2位の高さです。', 'are the Akaishi Mountains; the highest peak, Mount Kita at 3,193 meters, is the second-highest mountain in Japan.', '赤石(あかいし)。長野・山梨・静岡県に跨る。'],
  ['中央アルプス', 'the Central Alps', '木曽山脈のことで、最高峰の木曽駒ヶ岳は標高2,956メートルです。', 'are the Kiso Mountains; the highest peak, Mount Kiso-Komagatake, is 2,956 meters high.', ''],
  ['北アルプス', 'the Northern Alps', '飛騨山脈のことで、最高峰の奥穂高岳は標高3,190メートル、日本第3位の高さです。', 'are the Hida Mountains; the highest peak, Mount Okuhotaka at 3,190 meters, is the third-highest mountain in Japan.', '富山・岐阜・長野県に跨る。'],
  ['信濃川', 'the Shinano River', '長さ367キロメートルの日本一長い川で、長野県では千曲川と呼ばれます。', 'is the longest river in Japan at 367 kilometers; in Nagano Prefecture it is called the Chikuma River.', ''],
  ['佐渡島', 'Sado Island', '新潟県の沖に浮かぶ島です。', 'lies off the coast of Niigata Prefecture.', '読みは「さどしま」「さどがしま」どちらでも良いようです。'],
  ['木曽三川', 'the three Kiso rivers', '木曽川、長良川、揖斐川のことで、長良川は日本三大清流のひとつと言われています。', 'are the Kiso, Nagara and Ibi rivers; the Nagara is said to be one of the three clearest rivers in Japan.', '読みは「きそさんせん」。三大清流は柿田川・四万十川・長良川。'],
  ['千葉県', 'Chiba Prefecture', '日本で唯一、標高500メートル以上の山がない都道府県です。', 'is the only prefecture in Japan with no mountain higher than 500 meters.', '話題。'],
] },
{ r: '近畿', items: [
  ['琵琶湖', 'Lake Biwa', '面積約669平方キロメートル、日本最大の湖です。', 'is the largest lake in Japan, about 669 square kilometers.', ''],
  ['淀川', 'the Yodo River', '琵琶湖から流れ出る唯一の川で、支流の数は965本と日本一です。', 'is the only river flowing out of Lake Biwa, and has 965 tributaries, the most in Japan.', '瀬田川・宇治川・淀川と名前を変えて大阪湾へ。'],
  ['若狭湾', 'Wakasa Bay', '日本三景のひとつ、天橋立がある湾です。', 'is home to Amanohashidate, one of the Three Most Scenic Views of Japan.', '天橋立は湾内西部。'],
  ['明石海峡大橋', 'the Akashi Kaikyo Bridge', '全長3,911メートル、中央支間1,991メートルの吊り橋で、神戸市と淡路島を結んでいます。', 'is a suspension bridge 3,911 meters long, with a central span of 1,991 meters, linking Kobe and Awaji Island.', 'ハンドブックには「世界最長の吊り橋」とありますが、2022年にトルコの1915チャナッカレ橋(中央支間2,023m)が開通し、現在は世界第2位です。'],
  ['大鳴門橋', 'the Onaruto Bridge', '兵庫県南あわじ市と徳島県鳴門市を結ぶ、全長1,629メートルの橋です。', 'is a bridge 1,629 meters long, linking Awaji Island and Naruto in Tokushima Prefecture.', '読みは「おおなるときょう」。中央支間876m。'],
  ['淡路島', 'Awaji Island', '瀬戸内海で最大の島で、面積は約593平方キロメートルです。', 'is the largest island in the Seto Inland Sea, about 593 square kilometers.', ''],
  ['紀伊山地', 'the Kii Mountains', '三重、奈良、和歌山の3県にまたがり、その一部は2004年に「紀伊山地の霊場と参詣道」として世界文化遺産に登録されました。', 'span Mie, Nara and Wakayama prefectures, and part of them was registered in 2004 as the World Heritage Site "Sacred Sites and Pilgrimage Routes in the Kii Mountain Range".', ''],
  ['潮岬', 'Cape Shionomisaki', '本州の最南端です。', 'is the southernmost point of Honshu.', ''],
] },
{ r: '中国・四国', items: [
  ['瀬戸内海', 'the Seto Inland Sea', '東西約440キロメートルにわたり、最大の島は淡路島、2番目は小豆島です。', 'stretches about 440 kilometers from east to west; its largest island is Awaji Island, followed by Shodoshima.', ''],
  ['中国山地', 'the Chugoku Mountains', '兵庫県から山口県まで約500キロメートルにわたって連なっています。', 'stretch about 500 kilometers from Hyogo to Yamaguchi Prefecture.', '地質学的な山脈の定義に当てはまらないため「山脈」ではなく「中国山地」。'],
  ['瀬戸大橋', 'the Great Seto Bridge', '岡山県倉敷市と香川県坂出市を結ぶ、10の橋の総称です。', 'is a series of ten bridges linking Kurashiki in Okayama and Sakaide in Kagawa.', ''],
  ['大山', 'Mount Daisen', '中国地方の最高峰で標高1,729メートル、「伯耆富士」とも呼ばれます。', 'is the highest mountain in the Chugoku region, at 1,729 meters, and is also known as "Hoki Fuji".', '読みは「だいせん」「ほうきふじ」。'],
  ['宍道湖と中海', 'Lake Shinji and Lake Nakaumi', '海水と淡水が混じり合う汽水湖です。', 'are brackish lakes, where fresh water and sea water mix.', '読みは「しんじこ」「なかうみ」「きすいこ」。'],
  ['厳島', 'Itsukushima', '「安芸の宮島」とも呼ばれる日本三景のひとつで、厳島神社は1996年に世界文化遺産に登録されました。', ', also known as Miyajima, is one of the Three Most Scenic Views of Japan, and Itsukushima Shrine was registered as a World Heritage Site in 1996.', '読みは「いつくしま」。'],
  ['吉野川', 'the Yoshino River', '長さ194キロメートル、日本三大暴れ川のひとつで、「四国三郎」とも呼ばれます。', 'is one of the three great wild rivers of Japan, 194 kilometers long, and is also called "Shikoku Saburo".', '利根川(坂東太郎)・筑後川(筑紫次郎)と並ぶ。'],
  ['剣山', 'Mount Tsurugi', '徳島県の最高峰で、日本百名山のひとつ、標高1,955メートルです。', 'is the highest mountain in Tokushima Prefecture, at 1,955 meters, and one of the 100 Famous Mountains of Japan.', '読みは「つるぎさん」。'],
  ['四万十川', 'the Shimanto River', '長さ196キロメートル、日本三大清流のひとつと言われています。', 'is 196 kilometers long and is known as one of the three clearest rivers in Japan.', '読みは「しまんとがわ」。'],
  ['仁淀川', 'the Niyodo River', '長さ124キロメートル、水質の良さで知られる川です。', 'is 124 kilometers long and is known for its exceptionally clear water.', '吉野川・四万十川に次ぐ四国第三の河川。'],
  ['石鎚山', 'Mount Ishizuchi', '近畿以西の西日本の最高峰で、標高1,982メートルです。', 'is the highest mountain in western Japan, at 1,982 meters.', '読みは「いしづちさん」。'],
  ['佐田岬半島', 'the Sadamisaki Peninsula', '日本一細長い半島と言われています。', 'is said to be the longest and narrowest peninsula in Japan.', '読みは「さだみさきはんとう」。'],
] },
{ r: '九州', items: [
  ['長崎県', 'Nagasaki Prefecture', '都道府県別で島の数が日本一です。', 'has more islands than any other prefecture in Japan.', 'ハンドブックでは島の数971。2023年に国土地理院が島の数を数え直しており数値が変わっているため、PAでは数を言わない形にしています。'],
  ['阿蘇くじゅう国立公園', 'Aso-Kuju National Park', '阿蘇山(標高1,592メートル)や九重連山など、1,700メートル級の山々が連なっています。', 'is home to Mount Aso, 1,592 meters high, and the Kuju mountains, with peaks of around 1,700 meters.', '九重連山(中岳)は標高1,791m。'],
  ['筑後川', 'the Chikugo River', '長さ143キロメートル、日本三大暴れ川のひとつで、「筑紫次郎」とも呼ばれます。', 'is one of the three great wild rivers of Japan, 143 kilometers long, and is also called "Tsukushi Jiro".', '読みは「つくしじろう」。'],
  ['雲仙岳', 'Mount Unzen', '{N}の最高峰は、標高1,483メートルの平成新山です。', "{N}'s highest peak is Heisei Shinzan, at 1,483 meters.", '平成新山(へいせいしんざん)。普賢岳は1,359m。'],
  ['別府温泉', 'Beppu Onsen', '源泉数は2,300か所以上、湧出量は日本一の温泉地です。', 'is a hot spring resort with more than 2,300 sources and the largest volume of hot spring water in Japan.', '湧出量は125,000キロリットル/日。'],
  ['霧島山', 'the Kirishima mountains', '宮崎県と鹿児島県の県境に広がる火山群で、最高峰の韓国岳は標高1,700メートルです。', 'are a group of volcanoes on the border of Miyazaki and Kagoshima; the highest, Mount Karakuni, is 1,700 meters high.', '韓国岳(からくにだけ)。'],
  ['桜島', 'Sakurajima', '標高1,117メートル、かつては島でしたが、1914年の噴火で大隅半島と陸続きになりました。', 'is 1,117 meters high; it was once an island, but the 1914 eruption connected it to the Osumi Peninsula.', ''],
  ['佐多岬', 'Cape Sata', '大隅半島の南端です。', 'is the southern tip of the Osumi Peninsula.', '読みは「さたみさき」。'],
  ['開聞岳', 'Mount Kaimon', '薩摩半島の南端にある標高924メートルの山で、「薩摩富士」と呼ばれます。', 'stands 924 meters high at the southern tip of the Satsuma Peninsula, and is known as "Satsuma Fuji".', ''],
  ['博多どんたく', 'the Hakata Dontaku festival', '例年5月3日から4日に開催されます。', 'is held every year on May 3rd and 4th.', '話題。'],
  ['博多祇園山笠', 'the Hakata Gion Yamakasa festival', '例年7月1日から15日に開催されます。', 'is held every year from July 1st to 15th.', '話題。'],
] },
{ r: '離島', items: [
  ['種子島', 'Tanegashima', '鉄砲伝来の地で、種子島宇宙センターがあり、日本の宇宙開発の一翼を担っています。', 'is where firearms were first introduced to Japan, and it is home to the Tanegashima Space Center.', ''],
  ['屋久島', 'Yakushima', '1993年に世界自然遺産に登録され、宮之浦岳(標高1,936メートル)は九州の最高峰です。', 'was registered as a World Natural Heritage Site in 1993, and Mount Miyanoura, at 1,936 meters, is the highest peak in Kyushu.', ''],
  ['奄美大島', 'Amami Oshima', '南西諸島では沖縄本島に次いで2番目に大きな島で、黒糖焼酎や大島紬が特産品です。', 'is the second-largest island in the Nansei Islands after Okinawa Island, and is known for brown sugar shochu and Oshima tsumugi silk.', '大島紬(おおしまつむぎ)。'],
  ['沖永良部島', 'Okinoerabu Island', '隆起サンゴ礁の島で、「花と鍾乳洞の島」とも呼ばれます。', 'is a raised coral island, also known as "the island of flowers and limestone caves".', '人口約15,000人。'],
  ['与論島', 'Yoron Island', '鹿児島県の最南端の島で、沖縄本島の辺戸岬まではわずか22キロメートルです。', 'is the southernmost island of Kagoshima Prefecture, just 22 kilometers from Cape Hedo on Okinawa Island.', ''],
  ['大東諸島', 'the Daito Islands', '南大東島、北大東島、沖大東島と周辺の小島からなる島々です。', 'consist of Minamidaito, Kitadaito and Okidaito islands and nearby islets.', '人口約2,100人。'],
  ['与那国島', 'Yonaguni Island', '日本の最西端の島です。', 'is the westernmost island of Japan.', ''],
  ['西表島', 'Iriomote Island', '沖縄県で2番目に大きな島で、イリオモテヤマネコやカンムリワシなどの特別天然記念物が生息しています。', 'is the second-largest island in Okinawa Prefecture, and is home to rare species such as the Iriomote wildcat, a Special Natural Monument.', '読みは「いりおもてじま」。石垣島の西。'],
  ['南西諸島', 'the Nansei Islands', '九州南端の大隅諸島から沖縄県全域までの島々です。', 'stretch from the Osumi Islands south of Kyushu across all of Okinawa Prefecture.', '話題。与那国島が日本最西端。'],
] },
];
function lmSentence(item) {            // 見どころの「一言」を作る
  const [nj, ne, fj, fe] = item;
  const ja = fj.includes('{N}') ? fj.replace('{N}', nj) : `${nj}は、${fj}`;
  const en = fe.includes('{N}') ? cap1(fe.replace('{N}', ne)) : cap1(ne) + (fe.startsWith(',') ? '' : ' ') + fe;
  return { ja, en };
}
